; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PortRegistry"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Haroon Abbasi"
#define MyAppURL "https://github.com/haroonabbasi/port-registry" ; Your source code URL
#define MyAppExeName "portregistry.exe"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Remove the next line if you want to allow installation without admin rights
PrivilegesRequired=lowest
OutputDir=installer
OutputBaseFilename=PortRegistry_Setup
; This ensures no "Setup" suffix is added to the installer exe
SetupIconFile=assets\portregistory.ico 
Compression=lzma
SolidCompression=yes
WizardStyle=modern

; This is the license file that will be shown during installation
LicenseFile=LICENSE.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The main executable from PyInstaller's dist folder
Source: "dist\portregistry.exe"; DestDir: "{app}"; Flags: ignoreversion
; Your environment template file
Source: ".env_example"; DestDir: "{app}"; Flags: ignoreversion
; Your application's license file
Source: "LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent