title: PortRegistry Docs
description: Documentation site for PortRegistry — architecture, dev setup, release & installer
baseurl: "/port-registry"
url: ""

# Theme settings
remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

# Mermaid support
mermaid:
  version: "10.6.1"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Navigation settings
aux_links:
  "PortRegistry on GitHub":
    - "https://github.com/haroonabbasi/port-registry"
